services:
  stride-project:
    restart: always
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./stride:/stride
      - ./media:/src/media
      - ./static:/src/static
      - ./staticfiles:/src/staticfiles
    env_file: .pg-env
    command: >
      sh -c "python manage.py migrate && gunicorn -w 3 config.wsgi --bind 0.0.0.0:8000"
    depends_on:
      - database

  database:
    restart: always
    image: postgres:14-alpine
    env_file: .pg-env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./stridecourses.crt:/etc/ssl/certs/stridecourses.crt:ro
      - ./stridecourses.key:/etc/ssl/private/stridecourses.key:ro
      - ./root_certificate.crt:/etc/ssl/certs/root_certificate.crt:ro
      - ./static:/src/static:ro
      - ./media:/src/media:ro
    depends_on:
      - stride-project
